name: Build Pipeline

on: push

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip install flit
      - run: make install
      - run: make lint

  build-docs:
    name: Build documentation
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/develop"]'), github.ref) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - run: pip install flit
      - run: make install
      - run: make build-docs
      - name: Push to docs-external-site
        uses: cpina/github-action-push-to-another-repository@v1.5
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DOCS_DEPLOY_KEY }}
        with:
          destination-github-username: caplena
          destination-repository-name: docs-external-site
          source-directory: docs/build/html/
          target-directory: public/sdk/python/
          user-email: admin@caplena.com
          target-branch: main
          commit-message: Update SDK documentation ORIGIN_COMMIT
